project_id = "gtmpqjbbcobjxwfeyqzz"

[functions.shippo-webhook]
verify_jwt = false

[functions.fedex-webhook]
verify_jwt = false

[functions.square-webhook]
verify_jwt = false

[functions.extract-label-data]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.send-system-notification]
verify_jwt = false

[functions.validate-address]
verify_jwt = false

[functions.calculate-shipping]
verify_jwt = false

[functions.validate-coupon]
verify_jwt = false

[functions.create-square-payment]
verify_jwt = false
